apiVersion: apps/v1
kind: Deployment
metadata:
  name: libros-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: libros
  template:
    metadata:
      labels:
        app: libros
    spec:
      containers:
      - name: libros
        image: mgerez/ddsdeploy:latest
        ports:
        - containerPort: 8070
        env:
        - name: PORT
          value: "8070"
        - name: javax__persistence__jdbc__user
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: javax__persistence__jdbc__password
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: "jdbc:postgresql://db:5432/dblibros"
        - name: javax__persistence__jdbc__url
          value: "jdbc:postgresql://db:5432/dblibros"
        - name: javax__persistence__jdbc__driver
          value: "org.postgresql.Driver"
        - name: hibernate__hbm2ddl__auto
          value: "create"
---
apiVersion: v1
kind: Service
metadata:
  name: libros-service
spec:
  selector:
    app: libros
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8070
  type: NodePort
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: YWRtaW4=
  POSTGRES_DB: ZGJsaWJyb3M=
