apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # postgres (base64 encoded)
  POSTGRES_PASSWORD: YWRtaW4=  # admin (base64 encoded)
  POSTGRES_DB: ZGJsaWJyb3M=  # dblibros (base64 encoded)
